#---------------------------------------
# Base image for runtime
FROM python:3.11-slim-bullseye as base

WORKDIR /usr/src/app
COPY ./api /usr/src/app/api/

RUN pip install -r api/requirements.txt
WORKDIR /usr/src/app/api
CMD ["uvicorn", "src.eng.app:app", "--host", "0.0.0.0", "--root-path", "/api", "--port", "8967"]

#---------------------------------------
